let itemCount = 1;
let data = [
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Coquette Shearling Lined Slipper (Women)",
    category: "shoes",
    gender: "female",
    price: "INR 10,540.95",
    review: "(3959)",
    img: "https://n.nordstrommedia.com/id/sr3/61e25487-c956-4f06-8ae8-3e3c9cb4532b.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Nordstrom",
    disc: "Moonlight Eco Pajamas",
    category: "cloths",
    gender: "female",
    price: "INR 3,953.63",
    review: "(71)",
    img: "https://n.nordstrommedia.com/id/sr3/bb08eea1-f884-487a-b077-16838db72eee.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Converse",
    disc: "Chuck Taylor® All Star® Lift High Top Platform Sneaker (Women)",
    category: "shoes",
    gender: "women",
    price: "INR 6,147.94",
    review: "(949)",
    img: "https://n.nordstrommedia.com/id/sr3/d3d9a69a-42cd-4a17-b925-57fc0398548e.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Dyson",
    disc: "Special Edition Supersonic™ Hair Dryer (Limited Edition)",
    category: "others",
    gender: "women",
    price: "INR 37,786.62",
    review: "(44)",
    img: "https://n.nordstrommedia.com/id/sr3/e67459fb-5776-4597-b1f7-af7106c0441d.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Scuffette II Slipper (Women)",
    category: "sliper",
    gender: "women",
    price: "INR 8,348.40",
    review: "(2728)",
    img: "https://n.nordstrommedia.com/id/sr3/75da7256-388b-4d3f-ac0e-010218f48e1d.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Ansley Water Resistant Slipper (Women)",
    category: "sliper",
    gender: "women",
    price: "INR 8,787.79",
    review: "(3928)",
    img: "https://n.nordstrommedia.com/id/sr3/af2691a8-eab7-456b-abc2-55ad158ad6f8.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Cozy Knit Genuine Shearling Slipper (Women)",
    category: "sliper",
    gender: "women",
    price: "INR 10,545.35",
    review: "(322)",
    img: "https://n.nordstrommedia.com/id/sr3/aa9df747-470c-4bbe-9d40-73e5d4e12408.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Jo Malone London™",
    disc: "Wood Sage & Sea Salt Cologne",
    category: "other",
    gender: "",
    price: "INR 7,030.23",
    review: "(1648)",
    img: "https://n.nordstrommedia.com/id/sr3/ada60d30-e5b2-4a25-92c5-d4c7fe67dc50.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "DIOR",
    disc: "Addict Lip Glow Balm",
    category: "other",
    gender: "women",
    price: "INR 3,339.36",
    review: "(3066)",
    img: "https://n.nordstrommedia.com/id/sr3/58e65ceb-a016-47a3-97ed-6e5752a1eafe.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Classic II Genuine Shearling Lined Short Boot (Women)",
    category: "shoes",
    gender: "women",
    price: "INR 14,939.24",
    review: "(2922)",
    img: "https://n.nordstrommedia.com/id/sr3/9fccd6b9-e97e-4fd9-a83b-09ad09cd4baf.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "NODPOD",
    disc: "Nod Pod Sleep Mask",
    category: "other",
    gender: "women",
    price: "INR 2,987.85",
    review: "(24)",
    img: "https://n.nordstrommedia.com/id/sr3/43aede3d-e203-4203-8de6-fd7b3be65836.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Nike",
    disc: "Air Force 1 '07 Sneaker (Men)",
    category: "shoes",
    gender: "male",
    price: "INR 9,666.57",
    review: "(1083)",
    img: "https://n.nordstrommedia.com/id/sr3/e1f5bfee-ee4f-439a-a7ff-5270d7825de0.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Ascot Slipper (Men)",
    category: "slipper",
    gender: "men",
    price: "INR 9,662.18",
    review: "(3581)",
    img: "https://n.nordstrommedia.com/id/sr3/dea98c12-40e0-4e97-9017-979ff0fe2859.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Hyde Slide Slipper (Men)",
    category: "slipper",
    gender: "male",
    price: "INR 8,787.79",
    review: "(8)",
    img: "https://n.nordstrommedia.com/id/sr3/8222eb9e-2d38-46ff-b6c7-1b8fa53b1eb5.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Fluff Yeah Faux Fur Slingback Sandal (Women)",
    category: "sandal",
    gender: "women",
    price: "INR 4,393.89",
    review: "(1705)",
    img: "https://n.nordstrommedia.com/id/sr3/f07dbade-1621-4bd0-8b56-5a344aa67b86.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "SKIMS",
    disc: "Soft Lounge Long Sleeve Dress (Regular & Plus Size)",
    category: "cloths",
    gender: "women",
    price: "INR 7,733.26C",
    review: "(592)",
    img: "https://n.nordstrommedia.com/id/sr3/090b01a3-be3b-4d57-8053-0171f2dc8618.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "Charlotte Tilbury",
    disc: "Pillow Talk Lip Secrets Set USD $79 Value",
    category: "other",
    gender: "women",
    price: "INR 4,306.02",
    review: "(4)",
    img: "https://n.nordstrommedia.com/id/sr3/2e662d23-0074-45b4-8cca-349824bf27e2.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Classic Short II Water Resistant Genuine Shearling Boot (Walker, Toddler, Little Kid & Big Kid)",
    category: "shoes",
    gender: "kids",
    price: "INR 9,139.30",
    review: "(1167)",
    img: "https://n.nordstrommedia.com/id/sr3/d409436c-cfcb-48ee-bc6d-afe8c82e2c89.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "DIOR",
    disc: "Rouge Dior Lip Coffret Gift Set",
    category: "other",
    gender: "female",
    price: "INR 16,696.80",
    review: "(1)",
    img: "https://n.nordstrommedia.com/id/sr3/0e0e30ec-6f93-4b33-9015-8c4ce97a5abb.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "SKIMS",
    disc: "Boyfriend Long Sleeve T-Shirt (Regular & Plus Size)",
    category: "cloths",
    gender: "men",
    price: "INR 6,590.84",
    review: "(38)",
    img: "https://n.nordstrommedia.com/id/sr3/5df81756-816e-4ca2-9c4f-fbe4fb5a715c.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
  {
    id: itemCount++,
    title: "UGG®",
    disc: "Lenny Robe",
    category: "cloths",
    gender: "female",
    price: "INR 7,803.56",
    review: "(5)",
    img: "https://n.nordstrommedia.com/id/sr3/cd8fe824-8120-49a6-b8f4-1e1f1d2a6078.jpeg?h=365&w=240&dpr=2",
    arrive: "Arrives before Christmas",
  },
];

let cards = document.getElementById("cards");

data.forEach((element, index) => {
  cards.innerHTML += `<div class="card-item">
<img
  src="${element.img}"
  alt="error"
/>
<div class="item-body">
  <div class="card-arrive">${element.arrive}</div>
  <div class="card-title">${element.title}</div>
  <h4 class="card-disc">
  ${element.disc}
  </h4>
  <div class="card-price">${element.price}</div>
  <div class="card-review">
    <span>Review:</span
    ><span class="review-counter">${element.review}</span>
  </div>
</div>
</div>`;
});
